### ISSUE TITLE
저도 할래요

### ISSUE THREAD

**Issue by 2wndrhs** [yourssu01-04s/react-deepdive#1]
나도 끼워달라

**Comment by 2wndrhs** [comment]
![image](https://github.com/yourssu-01s/react-deepdive/assets/76615094/8049f5b3-29d6-43f2-b853-a0dfda3f9e27)

$${\color{white}범인은 공민제}$$

**Comment by nijuy** [comment]
![1f97a](https://github.com/yourssu-01s/react-deepdive/assets/87255462/e958b0cd-6d98-4167-a7bb-88947a306f0b)
